### ISSUE TITLE
unit tests: order of arguments

### ISSUE THREAD

**Issue by glennj** [exercism/euphoria#52]
I see in std/unittest.e:
```
public procedure test_equal(sequence name, object expected, object outcome)
```

But many of the tests have `outcome` before `expected`.

That will lead to confusing test error messages. For example, in the raindrops exercise, if the number is not divisible by 3 or 5 or 7, I return the incorrect value "foo", and the test results say:
```
  failed: 2 to the power 3 does not make a raindrop sound as 3 is the exponent not the base, expected: "foo" but got: "8"
```

This will be a large effort to fix. I can help if you want to divide the labour.

**Comment by axtens** [comment]
There are 20 tasks. If you're happy to take the top 10....

**Comment by petelomax** [comment]
Added test_aquel() shim to flip the args, PR created for this, merged and closed.

**Comment by axtens** [comment]
All fixed https://github.com/exercism/euphoria/pull/76
