### ISSUE TITLE
two-fer: the stub gives away too much

### ISSUE THREAD

**Issue by glennj** [exercism/euphoria#55]
The two-fer exercise gives away the game:
```euphoria
--public function two_fer(sequence name = "you")

--end function
```

I'd suggest you don't show the default value, but provide an instructions.append.md 
that refers to [the procedures doc](https://openeuphoria.org/docs/lang_decl.html#_114_procedures)
which discusses default values.

**Comment by axtens** [comment]
https://github.com/exercism/euphoria/pull/62
