### ISSUE TITLE
[Track config.json]:  Exercises are not in an Obvious Order

### ISSUE THREAD

**Issue by BethanyG** [exercism/euphoria#65]
In looking at the tracks `config.json`, I noticed that exercises aren't ordered alphabetically nor by difficulty.

While that's fine (_and there may be an order I am not seeing here_), I do know that many students on other tracks have had expectations of steadily increasing difficulty, or some other "ordering" like exercise name when it comes to the exercise grid -- which is generated from the ordering in `config.json`.

Screengrab of an exercise grid for refrence:

<img width="934" alt="image" src="https://github.com/exercism/euphoria/assets/5923094/e2761685-8a24-4f91-bbfe-061a85f8ad55">

**Comment by axtens** [comment]
I'll put them in order of difficulty. Granted, there's an arbitrariness even there but some kind of order would be better than no order at all.

**Comment by axtens** [comment]
https://github.com/exercism/euphoria/pull/70

**Comment by petelomax** [comment]
On the Go track, there are easy, medium, and hard tags against each task, but not on the Euphoria track.
