### ISSUE TITLE
[Track config.json] Test_Runner Set to False

### ISSUE THREAD

**Issue by BethanyG** [exercism/euphoria#66]
Logging this because I don't know if it is intentional or not.  I see that there is a [euphoria test-runner repo](https://github.com/exercism/euphoria-test-runner), but  the `test_runner` field in the track's `config.json` is set to **false**.

If this is intentional, this can serve as a reminder to set it to true once the runner is available.  🙂

**Comment by axtens** [comment]
I believe it's available so will true this now and see what happens
