### ISSUE TITLE
[docs/ABOUT.md]: One-Sentence Per Line & Some Formatting Changes

### ISSUE THREAD

**Issue by BethanyG** [exercism/euphoria#67]
The `ABOUT.md` doc doesn't conform to our one-sentence-per-line rule. Please see [markdown spec](https://github.com/exercism/docs/blob/main/building/markdown/markdown.md) for more info.

Additionally, the final line:

> Euphoria has come a long way since v1.0 was released in July 1993 by Rapid Deployment Software (RDS). There are now enthusiastic users around the world.

Currently has a leading `#`, which makes the font render as a top-level header.  That should be removed.

Also suggest that the `Safe` section be broken out with bullets for easier reading.  Currently, its all one block which makes it harder to follow/understand.

**Comment by axtens** [comment]
https://github.com/exercism/euphoria/pull/71
