### ISSUE TITLE
[README.md]: Broken Configlet & Test links/badges

### ISSUE THREAD

**Issue by BethanyG** [exercism/euphoria#69]
<img width="1304" alt="image" src="https://github.com/exercism/euphoria/assets/5923094/34dbb76b-1795-40d4-9074-c05a28734914">

Not sure if it is across all browsers.

**Comment by axtens** [comment]
@ErikSchierboom ?

**Comment by petelomax** [comment]
Isn't it the Exercism Euphoria Track by now?

**Comment by axtens** [comment]
I started off, a couple of years ago, differentiating between the language and the implementation. It's all Euphoria now but the "Open" appears occasionally

**Comment by ErikSchierboom** [comment]
@axtens You can fix this in the [README](https://github.com/exercism/euphoria/blob/main/README.md).
The proper badge links can be found in the corresponding workflow page: https://github.com/exercism/euphoria/actions/workflows/configlet.yml

![image](https://github.com/exercism/euphoria/assets/135246/2ae58e89-9900-4c38-8cf3-fa2f623f656f)

**Comment by axtens** [comment]
https://github.com/exercism/euphoria/pull/73
