### ISSUE TITLE
path separators

### ISSUE THREAD

**Issue by petelomax** [exercism/euphoria#78]
I used include std\sequence.e on the Windows CLI but once uploaded it needs to be include std/sequence.e

Thankfully the latter works fine on both: should that be mentioned anywhere?

**Comment by ghaberek** [comment]
The [manual](https://github.com/OpenEuphoria/euphoria/blob/master/docs/refman_2.txt#L3894) suggests using forward slash for compatibility. I recommend _always_ using forward slash for include paths and leaving out quotes _unless_ the path contains spaces, in which case I recommend removing the spaces from the directory name, if possible.

> Note that under Windows, you can also use the forward slash '/' instead of the usually back-slash '\\'. By doing this, the file paths are compatible with _Unix_ systems and it means you don't have to 'escape' the back-slashes.
